### ISSUE TITLE
Possibility of using www.kuaishou.com/graphql over live.kuaishou.com LIVE_GET_FEEDS API

### ISSUE THREAD

**Issue by cydevdummy001** [Tommy131/KuaishouParser#12] opened 2023-03-26 11:04 UTC
**Is your feature request related to a problem? Please describe.**
Seems like the live.kuaishou.com has some stability issue (or my IP being silently banned 😢), always ended up getting [OwO/ERROR] > [KuaiModule] 无用户数据 after a few downloads. tried skipped the sensitive user info part and called LIVE_GET_FEEDS directly, the API is not working as well, returning empty data and result `2`

**Describe the solution you'd like**
Possible to leverage on operation `visionProfilePhotoList` provided by www.kuaishou.com/graphql instead of relying on live.kuaishou.com API?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Tommy131** [comment] 2023-03-26 16:23
Thank you for using this repository. Exactly, I got the same question like you. The cause of `live.kuaishou.com` 's server, they limit the request per minute / hour for client (IP). As I know for solution, you shouldn't request the target very often.
You mentioned change the alternative API to `www.kuaishou.com/graphl`. But the problem is, this API can't fetch the posted photos by the target (user). So in the last update I removed support for it.

**Comment by Tommy131** [comment] 2023-03-26 16:28
As far as I know, this is due to `did` in the cookie. The Kuaishou server will identify the client device through `did` to block it. Since this value is issued by the Kuaishou server, it is currently impossible to crack it with my ability. But you can try to log in through the web, get the cookie and copy it into the `config.json` file. The general ban time is about 1-2 days. It's really annoying, but I can't find an another solution for now :(

**Comment by cydevdummy001** [comment] 2023-03-27 14:09
Thanks for taking time to look into the issue Tommy! :) 

> But the problem is, this API can't fetch the posted photos by the target (user). So in the last update I removed support for it.

Actually I'm ok with skipping the images, can you point me to the commit where the `www.kuaishou.com/graphl` is still working?

**Comment by Tommy131** [comment] 2023-03-27 14:16
I'll try to retake the feature in the next commit. For personal reason I'm on busy this week, I'll work with it first in the next week.

**Comment by cydevdummy001** [comment] 2023-03-27 14:17
No rush Tommy, thanks again for creating this awesome repo 🙇

**Comment by Tommy131** [comment] 2023-03-27 14:19
> No rush Tommy, thanks again for creating this awesome repo 🙇

Should I add an English translate too?

**Comment by Tommy131** [comment] 2023-04-11 23:29
Dear user @cydevdummy001, I promised you to re-support API `www_graphql` usage. In the last 2 commits, the feature has been finalized. Check commit: https://github.com/Tommy131/KuaishouParser/commit/c8058ba467432fcb91669907bd23f42348698f7d

I closed this issue. If you have any question, feel free to repoen this issue and put your question(s) follow this comment.

**Closed as completed by Tommy131** 2023-04-11 23:29 UTC
Labels: enhancement, finished

**Comment by Tommy131** [comment] 2023-04-11 23:43
Please update the newest OwOFrame!

**Comment by cydevdummy001** [comment] 2023-04-23 15:10
Just tried it out, works perfectly, thanks Tommy.

FYI I encountered similar IP banning issue as before and resolved it by adding random sleep after complete download for each anchor.

**Comment by Tommy131** [comment] 2023-04-23 16:31
> Just tried it out, works perfectly, thanks Tommy.
> 
> FYI I encountered similar IP banning issue as before and resolved it by adding random sleep after complete download for each anchor.

I had added it before I commited this :) Sometimes it works but not always.
